apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-permissions-operator-cluster-admin
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
