apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-permissions-operator
  namespace: openshift-rbac-permissions
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
