apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest

objects:
- apiVersion: hive.openshift.io/v1alpha1
  kind: SelectorSyncSet
  metadata:
    generation: 1
    name: rbac-permissions-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
    resourceApplyMode: sync
    resources:
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: "true"
          opsrc-provider: redhat
        name: rbac-permissions-operator-registry
        namespace: openshift-monitoring
      spec:
        image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
        displayName: Rbac Permissions Operator
        icon:
          base64data: ""
          mediatype: ""
        publisher: Red Hat
        sourceType: grpc
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: rbac-permissions-operator
        namespace: openshift-monitoring
      spec:
        channel: ${CHANNEL}
        name: rbac-permissions-operator
        source: rbac-permissions-operator-registry
        sourceNamespace: openshift-monitoring