// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermission":       schema_pkg_apis_managed_v1alpha1_GroupPermission(ref),
		"github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermissionSpec":   schema_pkg_apis_managed_v1alpha1_GroupPermissionSpec(ref),
		"github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermissionStatus": schema_pkg_apis_managed_v1alpha1_GroupPermissionStatus(ref),
	}
}

func schema_pkg_apis_managed_v1alpha1_GroupPermission(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GroupPermission is the Schema for the grouppermissions API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermissionSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermissionStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermissionSpec", "github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.GroupPermissionStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_managed_v1alpha1_GroupPermissionSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GroupPermissionSpec defines the desired state of GroupPermission",
				Properties: map[string]spec.Schema{
					"groupName": {
						SchemaProps: spec.SchemaProps{
							Description: "Name of the Group granted permissions by the operator",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"clusterPermissions": {
						SchemaProps: spec.SchemaProps{
							Description: "List of permissions applied at Cluster scope",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.ClusterPermission"),
									},
								},
							},
						},
					},
					"permissions": {
						SchemaProps: spec.SchemaProps{
							Description: "List of permissions applied at Namespace scope",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.Permission"),
									},
								},
							},
						},
					},
				},
				Required: []string{"groupName"},
			},
		},
		Dependencies: []string{
			"github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.ClusterPermission", "github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.Permission"},
	}
}

func schema_pkg_apis_managed_v1alpha1_GroupPermissionStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GroupPermissionStatus defines the observed state of GroupPermission",
				Properties: map[string]spec.Schema{
					"conditions": {
						SchemaProps: spec.SchemaProps{
							Description: "List of conditions for the CR",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.Condition"),
									},
								},
							},
						},
					},
					"state": {
						SchemaProps: spec.SchemaProps{
							Description: "State that this condition represents",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"state"},
			},
		},
		Dependencies: []string{
			"github.com/openshift/rbac-permissions-operator/pkg/apis/managed/v1alpha1.Condition"},
	}
}
